### ISSUE TITLE
vtt subtitles not working?

### ISSUE THREAD

**Issue by muranava** [Baozisoftware/nextcloud-videoplayer#1]
hi
i can't seem to get the VTT subtitles working?
thanks

**Comment by Baozisoftware** [comment]
See [Node](https://github.com/Baozisoftware/nextcloud-videoplayer#note),vtt should be the standard format, you can create it using ffmpeg.for the language part, please read the [source code](https://github.com/Baozisoftware/nextcloud-videoplayer/blob/master/js/viewer.js#L174).
