### ISSUE TITLE
How install it on 16.0.2

### ISSUE THREAD

**Issue by robsoncloud** [Baozisoftware/nextcloud-videoplayer#2]
Hi friend,

I would like to know how can I install your video player version on my own server?

Whenever I try to install the server kick out an upgrade and replace the folder files_videoplayer contents.

Thank you

**Comment by Baozisoftware** [comment]
[installation](https://github.com/Baozisoftware/nextcloud-videoplayer#installation) said:
**disable** _Video player_ and _Viewer_ app.
