### ISSUE TITLE
Nextcloud 18 support?

### ISSUE THREAD

**Issue by hrenki** [Baozisoftware/nextcloud-videoplayer#4]
Hi, i cant get this to work on nextcloud 18... 
Viewer app is not in apps list anymore, so i tried renaming viewer app folder and installing nextcloud-videoplayer as described but it fails to play anything, it goes straight to download.

Seems that default videoplayer is not functioning either, and that Viewer app is playing all the files

**Comment by Baozisoftware** [comment]
Sorry i can't do it,ask to official please.so i edit "**max-version**" to "**17**".

**Comment by adrianharabula** [comment]
I could not make it work on nextcloud 18 too...
