### ISSUE TITLE
没有字幕选项

### ISSUE THREAD

**Issue by BraveSail** [Baozisoftware/nextcloud-videoplayer#6]
![image](https://user-images.githubusercontent.com/49320262/99360955-55b12e00-28ec-11eb-87b7-05b212677a99.png)
![image](https://user-images.githubusercontent.com/49320262/99360986-5fd32c80-28ec-11eb-83ec-f1cfaf16ff41.png)

**Comment by Baozisoftware** [comment]
字母格式不对:
**Example:**
_Video file:[Blu-raws] Stand By Me Doraemon - MOVIE (BD 1920x1080 x264 Hi10P FLAC).mkv
Subtitles file:[Blu-raws] Stand By Me Doraemon - MOVIE (BD 1920x1080 x264 Hi10P FLAC).mkv_zh.vtt_
你似乎多了个"**.**".
